python/dailyfresh/cart/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^addcart', views.add_cart, name='add_cart'),
    url(r'^updatecart', views.update_cart, name='update_cart'),
    url(r'^delete', views.delete, name='delete'),
    url(r'^$', views.cart, name='cart')
]

python/dailyfresh/dailyfresh/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from product.views import home
from dailyfresh.settings import BASE_DIR
from django.shortcuts import render


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^search/', include('haystack.urls')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^product/', include('product.urls', namespace='product')),
    url(r'^$', home, name='home'),
]

python/dailyfresh/product/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'index/$', views.home, name='home'),
    url(r'detail/(?P<sku_id>\d+)$', views.detail, name='detail'),
    url(r'list/(?P<type>\d+)/(?P<page_num>\d+)/$', views.list, name='list'),
    # url(r'$', views.home, name='home'),
]

python/dailyfresh/user/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^register/checkname/(?P<name>\w+)$', views.check_name, name='checkname'),
    url(r'^register/active/(?P<token>.*)$', views.active_acount, name='active'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.tt_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^userinfo/$', views.user_info, name='userinfo'),
    url(r'^userorder/(\w+)$', views.user_order, name='userorder'),
    url(r'^useraddress', views.useraddress, name='useraddress'),
    # url(r'^useraddress', views.useraddress, name='useraddress'),
]

python/dailyfresh/templates/search/search.html
{%extends 'base.html'%}
{% block title%}
    列表页
{% endblock %}
{% block header %}
    <div class="search_bar clearfix">
    <a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
    <form method='get' action="/search/" target="_blank">
        <div class="search_con fl">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
        </div>
    </form>


    {% if user.is_authenticated %}
  <div class="guest_cart fr">
        <a href="/cart/" class="cart_name fl">我的购物车</a>
        <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
    </div>
        {% else %}
        <div class="guest_cart fr">
            <a href="{% url 'user:login' %}" class="cart_name fl">我的购物车</a>
        </div>
    {% endif %}
</div>
    <div class="navbar_con">
    <div class="navbar clearfix">
        <div class="subnav_con fl">
            <h1>全部商品分类</h1>
            <span></span>
            <ul class="subnav">
                {% for type in types %}
                <li><a href="{% url 'product:list' type.id 1 %}" class="{{ type.logo }}">{{ type.category_name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <ul class="navlist fl">
            <li><a href="">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">手机生鲜</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>
</div>
{% endblock %}
{% block main %}
<div class="r_wrap fr clearfix">
    <ul class="goods_type_list clearfix">
        {%for p in page %}
        <li>
            <a href="{% url 'product:detail' p.object.id %}"><img src="{{ p.object.image }}"></a>
            <h4><a href="{% url 'product:detail' p.object.id %}">{{p.object.name}}</a></h4>
            <div class="operate">
                <span class="prize">￥{{p.object.price}}</span>
                <span class="unit">{{p.object.unite}}</span>
                <span class="unit">销量{{p.object.sales}}</span>
                {% if request.session.user_name|default:'' != '' %}
					<a href="javascript:;" id="{{ g.id }}" class="add_goods" title="加入购物车"></a>
				{% else %}
      				<a href="/user/login/" class="add_goods" title="加入购物车"></a>
				{% endif %}
            </div>
        </li>
        {%endfor%}
    </ul>

    <div class="pagenation">
        {% if page.has_previous %}
        <a href="/search?q={{ query }}&page={{ page.previous_page_number }}">上一页</a>
        {% endif %}
        {%for pindex in paginator.page_range%}
        <!--如果选择的是当前页，则标记为活动样式-->
        {%if pindex == page.number%}
        <a href="/search?q={{ query }}&page={{ pindex }}" class="active">{{pindex}}</a>
        {%else%}
        <a href="/search?q={{ query }}&page={{ pindex }}">{{pindex}}</a>
        {%endif%}
        {%endfor%}
        {% if page.has_next %}
        <a href="/search?q={{ query }}&page={{ page.next_page_number }}">下一页></a>
        {% endif %}
    </div>
</div>
{%endblock main%}

python/dailyfresh/templates/search/search1.html
{%extends 'base.html'%}
{% block title%}
    列表页
{% endblock %}
{% block header %}
    <div class="search_bar clearfix">
    <a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
    <form method='get' action="/search/" target="_blank">
        <div class="search_con fl">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
        </div>
    </form>


    {% if user.is_authenticated %}
  <div class="guest_cart fr">
        <a href="/cart/" class="cart_name fl">我的购物车</a>
        <div class="goods_count fl" id="show_count">{{ cart_count }}</div>
    </div>
        {% else %}
        <div class="guest_cart fr">
            <a href="{% url 'user:login' %}" class="cart_name fl">我的购物车</a>
        </div>
    {% endif %}
</div>
    <div class="navbar_con">
    <div class="navbar clearfix">
        <div class="subnav_con fl">
            <h1>全部商品分类</h1>
            <span></span>
            <ul class="subnav">
                {% for type in types %}
                <li><a href="{% url 'product:list' type.id 1 %}" class="{{ type.logo }}">{{ type.category_name }}</a></li>
                {% endfor %}
            </ul>
        </div>
        <ul class="navlist fl">
            <li><a href="">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">手机生鲜</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>
</div>
{% endblock %}
{% block list %}
<div class="r_wrap fr clearfix">
    <div class="sort_bar">
        <a href="{% url 'product:list' current_type.id page.number %}?sort=default"
           {%if sort == "default"%}
        class="active"
        {%endif%}
        >默认</a>
        <a href="{% url 'product:list' current_type.id page.number %}?sort=price"
           {%if sort == "price"%}
        class="active"
        {%endif%}
        >价格</a>
        <a href="{% url 'product:list' current_type.id page.number %}?sort=sales"
           {%if sort == "sales"%}
        class="active"
        {%endif%}
        >人气</a>
    </div>
    <ul class="goods_type_list clearfix">
        {%for p in page %}
        <li>
            {{ page }}{{ paginator }}
            <a href="{% url 'product:detail' p.object.id %}"><img src="{{ p.object.image }}"></a>
            <h4><a href="{% url 'product:detail' p.object.id %}">{{p.object.name}}</a></h4>
            <div class="operate">
                <span class="prize">￥{{p.object.price}}</span>
                <span class="unit">{{p.object.unite}}</span>
                <span class="unit">销量{{p.object.sales}}</span>
                {% if request.session.user_name|default:'' != '' %}
					<a href="javascript:;" id="{{ g.id }}" class="add_goods" title="加入购物车"></a>
				{% else %}
      				<a href="/user/login/" class="add_goods" title="加入购物车"></a>
				{% endif %}
            </div>
        </li>
        {%endfor%}
    </ul>

    <div class="pagenation">
        {% if page.has_previous %}
        <a href="/search?q={{ query }}$page={{ page.previous_page_number }}">上一页</a>
        {% endif %}
        {%for pindex in paginator.page_range%}
        <!--如果选择的是当前页，则标记为活动样式-->
        {%if pindex == page.number%}
        <a href="/search?q={{ query }}$page={{ pindex }}" class="active">{{pindex}}</a>
        {%else%}
        <a href="/search?q={{ query }}$page={{ pindex }}">{{pindex}}</a>
        {%endif%}
        {%endfor%}
        {% if page.has_next %}
        <a href="/search?q={{ query }}$page={{ page.next_page_number }}">下一页></a>
        {% endif %}
    </div>
</div>
{%endblock list%}